### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by MaartenFaddegon** [brandonhamilton/purescript-phoenix#3]
I cannot run the example code. Am I missing something or is there an incompatibility with Purescript version 0.11.6?

To reproduce:

Create a new project with `pulp init && bower install purescript-phoenix`

Copy the [example code](https://github.com/brandonhamilton/purescript-phoenix/issues/1) into `src/Main.purs`.

When trying to run the example with `pulp run` I get the unexpected output
```
...
Compiling Phoenix
Compiling Main
Compiling Data.Map.Gen
* Build successful.
1. Creating
/home/maarten/Purescript/hello/output/Phoenix/foreign.js:5
      return new window.Phoenix.Socket(endpoint, options);
                 ^

ReferenceError: window is not defined
    at /home/maarten/Purescript/hello/output/Phoenix/foreign.js:5:18
    at Object.__do [as main] (/home/maarten/Purescript/hello/output/Main/index.js:64:212)
    at Object.<anonymous> (/tmp/pulp-run117630-6785-zn62c0.vc4s.js:1:79)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
* ERROR: Subcommand terminated with exit code 1
```

**Comment by brandonhamilton** [comment]
purescript-phoenix is meant to run in a client-side browser environment alongside the [phoenix.js client library](https://github.com/phoenixframework/phoenix/blob/v1.2/web/static/js/phoenix.js).

However, the `pulp run` command will build and then run your code using `node`, which does not define [`window`](https://developer.mozilla.org/en/docs/Web/API/Window).

To get started with purescript-phoenix, the purescript code can be compiled into a single javascript file  with the `pulp build --to` option, and can then be included and served from a phoenix project as a [static asset](https://hexdocs.pm/phoenix/static_assets.html).

**Comment by MaartenFaddegon** [comment]
Thanks for following up. 

I copied `main.js` to `assets/static/js/` in my Phoenix deployment, and in `app.html.eex` I added the following line

    <script src="<%= static_path(@conn, "/js/main.js") %>"></script>

Then, in the javascript console I get the error:

    TypeError: window.Phoenix is undefined[Learn More]  main.js:717:9
	    exports.newSocketImpl/</< http://localhost:4000/js/main.js:717:9
           __do http://localhost:4000/js/main.js:915:15
          <anonymous> http://localhost:4000/js/main.js:941:1

So am I still not running alongside the `phoenix.js` client library? From the guide you linked to I thought to understand that Phoenix always serves this alongside any asset?

**Comment by brandonhamilton** [comment]
If you are not using brunch (i.e. you created your phoenix project with `--no-brunch` option), you would need to manually include `phoenix.js` as well as your `main.js` (that you have put into `priv/static/js/`) in the template, e.g.

```eex
<script src="<%= static_path(@conn, "/js/phoenix.js") %>"></script>
<script src="<%= static_path(@conn, "/js/main.js") %>"></script>
```

If you are using brunch, you would need to incorporate your purescript code into the brunch build instead of directly including the `main.js` file in your html template. I suggest you look into the `pulp browserify` options. 
If you want a quick and dirty integration, just put your `main.js` from above into the `assets/js` directory, and include the following lines in `assets/js/app.js` to pull the purescript code into the brunch compiled script:

```javascript
global.Phoenix = require("phoenix");
require("./main");
```
